version: "3.9"

services:
  db:
    container_name: postgres_container
    build: 
      context: .
      dockerfile: postgresDockerFile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    restart: always
    networks:
      - postgres-connection

  hp-game:
    image: harry-potter-game
    container_name: harry-potter-game
    build:
      context: .
      dockerfile: gameDockerFile
    entrypoint: "tail -f /dev/null"
    volumes:
      - ".:/app"
    depends_on:
      - db
    restart: always
    networks:
      - postgres-connection

networks:
  postgres-connection:
    driver: bridge